### PR TITLE
[DONT MERGE] test_local_datasets fails

### PR DESCRIPTION
**Pull request by ArneBinder**
For now, this just adds `test_dataset_scripts.yml` github workflow that calls `nix -s tests_only_local_datasets`.

result:
```
=========================== short test summary info ============================
FAILED tests/data/test_dataset_common.py::LocalDatasetTest::test_load_real_dataset_all_configs_conll2002
FAILED tests/data/test_dataset_common.py::LocalDatasetTest::test_load_real_dataset_all_configs_wikiann
FAILED tests/data/test_dataset_common.py::LocalDatasetTest::test_load_real_dataset_conll2002
FAILED tests/data/test_dataset_common.py::LocalDatasetTest::test_load_real_dataset_wikiann
```

EDIT: May be fixed by #204

### CODE REVIEW

**Comment by ChristophAlt** [comment]
I don't understand this PR. What exactly is this about?

**Comment by ChristophAlt** [comment]
Ok, I see the failed tests. This is slightly complicated due to passing the `config_name` to the dataset builder but for the base builder we remove `config_name` from the `builder_kwargs`, setting it to None effectively, which is not allowed for datasets that have multiple configs and no default config. In any way this is not the desired behavior and is clearly a bug.

**Comment by ArneBinder** [comment]
Sorry, I was really not clear in the description, I created that mainly because I was really unsure if my local setup was broken and I wanted to execute the tests once at github CI.

**Comment by ArneBinder** [comment]
This was fixed by #204.

**Pull request closed without merging**
